### ISSUE TITLE
CS276 index build fails

### ISSUE THREAD

**Issue by aldebout** [florimondmanca/cs-ir#4]
En lancant `indexes buils CS276`, tout se passe bien jusqu'à
```
Flushed: tmp/1924
Finished consuming cache
Merging blocks…
Cleaning up blocks…
Traceback (most recent call last):
  File "/home/aldebout/.pyenv/versions/3.7.1/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/aldebout/.pyenv/versions/3.7.1/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/aldebout/Desktop/git_repos/cs-ir/indexes.py", line 300, in <module>
    indexes()
  File "/home/aldebout/.local/share/virtualenvs/cs-ir-PfdC3zh5/lib/python3.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/home/aldebout/.local/share/virtualenvs/cs-ir-PfdC3zh5/lib/python3.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/home/aldebout/.local/share/virtualenvs/cs-ir-PfdC3zh5/lib/python3.7/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/aldebout/.local/share/virtualenvs/cs-ir-PfdC3zh5/lib/python3.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/aldebout/.local/share/virtualenvs/cs-ir-PfdC3zh5/lib/python3.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/aldebout/Desktop/git_repos/cs-ir/indexes.py", line 295, in build
    build_index(collection, block_size=block_size, no_cache=True)
  File "/home/aldebout/Desktop/git_repos/cs-ir/indexes.py", line 165, in build_index
    return Index.build(collection, block_size=block_size)
  File "/home/aldebout/Desktop/git_repos/cs-ir/indexes.py", line 83, in build
    result = sorter.merge()
  File "/home/aldebout/Desktop/git_repos/cs-ir/indexes.py", line 250, in merge
    with multi_open(block_paths) as files:
  File "/home/aldebout/.pyenv/versions/3.7.1/lib/python3.7/contextlib.py", line 112, in __enter__
    return next(self.gen)
  File "/home/aldebout/Desktop/git_repos/cs-ir/utils.py", line 29, in multi_open
    yield [stack.enter_context(open(path)) for path in paths]
  File "/home/aldebout/Desktop/git_repos/cs-ir/utils.py", line 29, in <listcomp>
    yield [stack.enter_context(open(path)) for path in paths]
OSError: [Errno 24] Too many open files: 'tmp/151'
```

Il faudrait regarder du côté de la stack, voir s'il y a un paramètre de limite par défaut à changer. Sinon il faut rajouter du chunking :/

**Comment by florimondmanca** [comment]
Je crois que c'est une limite de l'OS (nombre max de fichiers ouvrables). Sur macOS ça passe mais peut-être que sur Linux c'est limité à 150 ? Car effectivement au moment de la fusion des blocs il les ouvre tous en même temps. Du coup faudrait faire une fusion en plusieurs étages :thinking:

**Comment by florimondmanca** [comment]
Je suis tombé sur https://askubuntu.com/a/460687

Résultat de la commande chez moi :

```
$ ulimit -a
-t: cpu time (seconds)              unlimited
-f: file size (blocks)              unlimited
-d: data seg size (kbytes)          unlimited
-s: stack size (kbytes)             8192
-c: core file size (blocks)         0
-v: address space (kbytes)          unlimited
-l: locked-in-memory size (kbytes)  unlimited
-u: processes                       709
-n: file descriptors                4864
```

J'ai bien un nb de descripteurs > 1500. Mais vaudrait mieux qu'on limite pour que tout le monde ne soit pas obligé de faire la modif.

**Comment by florimondmanca** [comment]
@aldebout J'ai pas encore eu le temps d'y regarder, et j'ai potentiellement la flemme au vu de ce qu'il reste à faire. Tu as essayé de relancer en augmentant le nb de fichiers max comme indiqué dans le lien ?

**Comment by aldebout** [comment]
On laisse comme ça, ça passe en augmentant, merci.
